const { SlashCommandBuilder } = require("@discordjs/builders");

const horny_goodnight = [
  `Thinking of you. Sleep well!`,
  `If you promise to dream of me, I promise to dream of you.`,
  `Goodnight! I’m sending warm hugs and sweet kisses to you.`,
  `Goodnight, my angel.`,
  `You’re the best! Just wanted to let you know before bed.`,
  `Wishing you the best day tomorrow, honey.`,
  `Sleep well. I love you.`,
  `Miss you. Have a good sleep.`,
  `Good night to the most beautiful person on earth.`,
  `Sleep well. But if you get insomnia, I’m just a text away!`,
  `I’m so grateful for your presence in my life, even when we’re not together. Good night!`,
  `I just couldn’t sleep without saying I love you. Good night, my love.`,
  `My name is written on your lips, and my love is written in your heart. Good night.`,
  `The night sky of my life has only one star and that’s you. Good night.`,
  `I love you more every day. Good night.`,
  `Sleep well. You are my favorite dream.`,
  `Tomorrow night, I’ll kiss you to sleep. Tonight, I’ll just dream about it.`,
  `My prayer is that you will always fall asleep knowing how deeply you are loved.`,
  `If I were the Sandman, I’d add extra sparkle to your sand, and extra sweetness to your dreams.`,
  `You’re probably asleep, but I want this to be the first thing you see in the morning: I love you.`,
  `Dreaming that I wake up beside you tomorrow morning. Good night, love.`,
  `Sending you a million kisses before you close your eyes. Love you and good night.`,
  `I love getting to be the person who tells you goodnight—tonight and every night!`,
  `May the angels watch over you as you sleep, my love.`,
  `If you get cold tonight, I hope you feel the warmth of my love blanketing you.`,
  `May your dreams be filled with happiness, just like you fill my heart with joy.`,
  `Good night, love. If you have a nightmare, don’t call me. I need my beauty sleep!`,
  `Sleep well and dream of your favorite person…me!`,
  `Sleep well and dream of me…or pizza—whichever you prefer.`,
  `Hoping you savor a night without my snoring. Sleep well!`,
  `There’s a reason they call it ‘beauty sleep.’ And you’re the poster child!`,
  `Let the monsters under your bed know they’re going to have a stern talking to if they keep you up.`,
  `Baby, you must be exhausted from looking so good all the time!`,
  `I’d call and sing you a lullaby, but that would probably cause you nightmares.`,
  `The Beatles may have believed that all you need is love, but they were wrong. All you really need is sleep. Luckily, I got both!`,
  `Hurry and go to sleep…so you can dream of me!`,
  `Sleep tight and don’t forget to set your alarm so you can hit ‘Snooze’ ten times in the morning.`,
  `Good night, love.`,
  `Goodnight, I miss you!`,
  `Good night, sleep tight.`,
  `Good night, babe.`,
  `Good night, you are loved.`,
  `Good night. I love you.`,
  `Good night, honey.`,
  `Hope you had a great day. Good night.`,
  `Thinking of you. Good night.`,
  `Hasta mañana! See you in the morning.`,
  `Miss you already. Good night, love!`,
  `My dreams would only be sweeter if you were here. Good night, love you.`,
  `Good night! May all your dreams be as beautiful as you are.`,
  `I wish we didn’t have to sleep, so we could just keep talking!`,
  `My bed feels so empty without you in it.`,
  `I think we really ought to move in together at this point. Texting ‘good night’ isn’t cutting it.`,
  `I’m already looking forward to your good morning text.`,
  `NGL, I might be up all night thinking about you!`,
  `I’m only a text away if you feel lonely tonight…`,
  `If we were together, I’m sure we wouldn’t be getting any sleep tonight!`,
  `I want your face to be the last thing I see at night and the first thing I see in the morning.`,
  `Sleep tight and enjoy the lovely dreams coming your way…of me, I hope.`,
  `As much as I’d love to keep you up, I’ll let you get some sleep.`,
  `I go to bed every day feeling like I won the lottery because of you.`,
  `Sending you a big Texas-sized hug before you drift off to sleep.`,
  `I hope you had the best day! Missing you always.`, 
  `Don't forget to count your blessings before counting sheep. Love you!`, 
  `Sleep tight, darlin'. I'll be dreaming of you.`, 
  `Good night, wishing I was sleeping next to you!`, 
  `You're the best! Just wanted to let you know before bed.`, 
  `Sweetest dreams to the sweetest person.`
  ]
const goodnight = [
  `Night, night.`,
  `Have the sweetest of dreams.`,
  `Savor your rest, you deserve it.`,
  `Good night. Sleep tight. Don’t let the bedbugs bite.`,
  `Sleep like a bear in hibernation!`,
  `Why are you still awake? Go to bed!`,
  `Sweet dreams.`,
  `Good night, I hope you have a nice night.`,
  `Counting down the hours till I see you... but for now, good night.`, 
  `Nighty-night! Sleep tight and don't let the bedbugs bite.`, 
  `Hoping you rest easy. Good night my sweets.`, 
  `Rest easy, friend. Tomorrow's a new day full of possibilities.`, 
  `Hasta mañana! See you in the morning.`, 
  `Wrap yourself up in a cozy blanket and drift off to dreamland. Good night!`, 
  `The moon is shining bright, but you shine brighter. Sleep well, my dear.`, 
  `What a treat, talking to you before bed. Sleep well!`, 
  `Hope you have the sweetest dreams tonight.`, 
  `Rest your head on that pillow and let your worries drift away.`, 
  `Good night, love. Dream big, sleep well, and wake up ready to conquer the day!`, 
  `Sleep well and dream big.`, 
  `Good night, pookie head!`, 
  `Sweet dreams. I can't wait to see you soon!`, 
  `Good night, good sleep, good vibes.`, 
  `Sleep well, my friend. Don't let the bed bugs bite, but if they do, you better bite back.`, 
  `Good night, love. If you have a nightmare, don't call me. I need my beauty sleep!`, 
  `I think we really ought to move in together at this point. Texting "good night" isn't cutting it.`, 
  `Sleep tight and don't forget to set your alarm so you can hit snooze ten times in the morning.`, 
  `Good night! May your dreams be as weird and wonderful as you are.`, 
  `Sleep well and dream of a world where Monday mornings don't exist.`, 
  `Missing you my starfish. Yes, you totally take up the whole bed and I love it.`, 
  `Psst: time to close your eyes!`, 
  `Good night love! (This is your sign to put your phone down.)`, 
  `Don't forget to brush your teeth! And floss! Okay, that's it—good night.`, 
  `Hoping your dreams aren't too weird tonight!`, 
  `Sleep well and dream of me...or pizza. Whichever you prefer.`, 
  `Good night, sleep well, and remember that tomorrow is another day to procrastinate.`, 
  `Wishing you a good night's sleep... or at least a few hours of pretending to sleep until you finally pass out.`, 
  `Sleep like a bear in hibernation!`, 
  `May your sleep be peaceful and your snoring be kept to a minimum.`, 
  `I hope you dream of crying monkeys and talking babies...oh wait.`, 
  `Let the monsters under the bed know we're going to have a stern talking to if they keep you up.`,
  `I wish God to hold you tight. I hope the angels will keep you bright. To make sure you feel good, I’m going to wish you a good night.`, 
  `If my love can help you have a great night, then I send it to you with all my heart.`, 
  `I send you two angels to watch over you while you are in a dreamy world! Good night, bestie!`, 
  `Before you go to bed, look out your window, and the stars you will see are the thousands of hugs I send you.`, 
  `You are the moon that lights up the sky at night; you are that star that shines brightly; you are that girl who was blessed in the moonlight. Good night, best friend!`, 
  `Enjoy the nice cool breeze and sleep well tonight! Good night!`, 
  `Dear friend, I send you my loving thoughts to wish you a good night.”`, 
  `My compadre, without you, I would be lost. May your night be peaceful, sweet, and full of serenity.`, 
  `The weight of a message is so light that I can load it with love and tenderness to make sure you have the sweetest of nights. Sleep well.`, 
  `You may be far from me tonight, but I do not forget, as I do every night, to wish you the most beautiful night, full of starry dreams. I miss you, bud!`, 
  `I thought I was the most unforgettable soul in the world, but then you happened and made me feel like the luckiest being! Thanks a ton for being my best buddy!. Good night!`,
  `As the sun sets, lovers send each other hugs and kisses while friends send warm wishes. Hope this night brings you some good karma that will encourage you to make all dreams come true. Good night.`, 
  `I shall always be there for you to remove all the dark clouds above your head and gather all the happiness you need. Good night!`, 
  `I could have sent you a funny joke, an inspirational statement, or a sweet message. Yet I have decided to remind you that we are the closest friends. Good night.`, 
  `You have the patience to have me, and that is why I rush to you when I need someone to converse with. Very much obliged to be your friend. Good night, my perfect pal!`, 
  `Close your eyes, I will hold you tight, and I guarantee you that I will protect you for the rest of your life too. Good night!`
  ]
const hello = [
  `Hello!`, 
  `Hi there!`, 
  `Hey!`, 
  `Greetings!`, 
  `Howdy!`, 
  `What's up?`, 
  `How are you doing?`, 
  `How's it going?`, 
  `Wassup?`, 
  `Good to see you!`, 
  `Hiya!`, 
  `How are things?`, 
  `How's life treating you?`, 
  `Nice to meet you!`, 
  `Long time no see!`, 
  `What's cracking?`, 
  `Salutations!`, 
  `Top of the morning to you!`, 
  `Hey, friend!`, 
  `How have you been?`, 
  `Yo!`, 
  `Pleased to meet you!`, 
  `What's the good word?`, 
  `What's happening?`, 
  `How's your day?`, 
  `How's everything?`, 
  `How's your week going?`, 
  `It's a pleasure to see you!`, 
  `How's your day treating you so far?`, 
  `Hey, stranger!`, 
  `Aloha!`, 
  `How's your family?`, 
  `How's your job?`, 
  `G'day!`, 
  `How's your health?`, 
  `How's your weekend?`, 
  `How's your Monday?`, 
  `How's your Tuesday?`, 
  `How's your Wednesday?`, 
  `How's your Thursday?`, 
  `How's your Friday?`, 
  `How's your Saturday?`, 
  `How's your Sunday?`, 
  `Good day!`, 
  `How's your morning?`, 
  `How's your afternoon?`, 
  `How's your evening?`, 
  `How's your night?`, 
  `How's your lunch?`, 
  `How's your dinner?`, 
  `How's your coffee?`, 
  `How's your tea?`, 
  `How's your workout?`, 
  `How's your reading?`, 
  `How's your writing?`, 
  `How's your day job?`, 
  `How's your hobby?`, 
  `How's your project?`, 
  `How's your journey?`, 
  `How's your adventure?`, 
  `How's your travel?`, 
  `How's your pet?`, 
  `How's your garden?`, 
  `How's your cooking?`, 
  `How's your music?`, 
  `How's your movie?`, 
  `How's your book?`, 
  `How's your game?`, 
  `How's your exercise?`, 
  `How's your art?`, 
  `How's your sleep?`, 
  `How's your dream?`, 
  `How's your goal?`, 
  `How's your challenge?`, 
  `How's your achievement?`, 
  `How's your success?`, 
  `How's your failure?`, 
  `How's your lesson?`, 
  `How's your learning?`, 
  `How's your skill?`, 
  `How's your talent?`, 
  `How's your passion?`, 
  `How's your happiness?`, 
  `How's your sadness?`, 
  `How's your laughter?`, 
  `How's your joy?`, 
  `How's your love?`, 
  `How's your friendship?`, 
  `How's your relationship?`, 
  `How's your family time?`, 
  `How's your alone time?`, 
  `How's your self-care?`, 
  `How's your self-love?`, 
  `How's your mindfulness?`, 
  `How's your meditation?`, 
  `How's your reflection?`, 
  `How's your gratitude?`, 
  `How's your kindness?`, 
  `How's your generosity?`, 
  `How's your day going so far?`
  ]
const goodmorning = [
  `Good morning!`, 
  `Morning!`, 
  `Good day!`, 
  `Top of the morning to you!`, 
  `Rise and shine!`, 
  `Hello, sunshine!`, 
  `Wakey, wakey!`, 
  `Good morning, beautiful!`, 
  `Good morning, handsome!`, 
  `Hello, good-looking!`, 
  `Bonjour!`, 
  `Buenos días!`, 
  `G'morning!`, 
  `Hey there, morning person!`, 
  `Happy morning!`, 
  `It's a brand new day!`, 
  `Good morning to you!`, 
  `Wishing you a bright morning!`, 
  `Rise and sparkle!`, 
  `Good morning, world!`, 
  `Good morning, sunshine!`, 
  `Hello, Monday (or any day of the week)!`, 
  `Good morning, friend!`, 
  `Sending morning smiles!`, 
  `Morning vibes!`, 
  `Greetings, early bird!`, 
  `Good morning, starshine!`, 
  `A beautiful morning to you!`, 
  `Rise and grind!`, 
  `Greetings, morning enthusiast!`, 
  `Hello, new day!`, 
  `Good morning, lovely!`, 
  `Wishing you a cheerful morning!`, 
  `Morning magic!`, 
  `Rise and conquer!`, 
  `Hello, Tuesday (or any day of the week)!`, 
  `Good morning, neighbor!`, 
  `Morning glory!`, 
  `A blessed morning to you!`, 
  `Rise and radiate positivity!`, 
  `Good morning, bestie!`, 
  `Hello, Wednesday (or any day of the week)!`, 
  `Wishing you a joyful morning!`, 
  `Morning serenity!`, 
  `Rise and excel!`, 
  `Good morning, buddy!`, 
  `Hello, Thursday (or any day of the week)!`, 
  `Morning tranquility!`, 
  `A fantastic morning to you!`, 
  `Rise and thrive!`, 
  `Good morning, pal!`, 
  `Hello, Friday (or any day of the week)!`, 
  `Morning bliss!`, 
  `Sending morning happiness!`, 
  `Rise and conquer the day!`, 
  `Good morning, chum!`, 
  `Hello, Saturday (or any day of the week)!`, 
  `Morning peace!`, 
  `A splendid morning to you!`, 
  `Rise and shine bright!`, 
  `Good morning, mate!`, 
  `Hello, Sunday (or any day of the week)!`, 
  `Morning calm!`, 
  `Wishing you a peaceful morning!`, 
  `Rise and embrace the day!`, 
  `Good morning, comrade!`, 
  `Hello, weekend (or any day of the week)!`, 
  `Morning zen!`, 
  `A refreshing morning to you!`, 
  `Rise and be amazing!`, 
  `Good morning, compadre!`, 
  `Hello, sunshine day!`, 
  `Morning tranquility!`, 
  `Wishing you a serene morning!`, 
  `Rise and shine like never before!`, 
  `Good morning, partner!`, 
  `Hello, new dawn!`, 
  `Morning delight!`, 
  `A wonderful morning to you!`, 
  `Rise and radiate joy!`, 
  `Good morning, sidekick!`, 
  `Hello, golden morning!`, 
  `Morning joy!`, 
  `Wishing you a bright and cheerful morning!`, 
  `Rise and conquer the sunrise!`, 
  `Good morning, confidant!`, 
  `Hello, radiant morning!`, 
  `Morning harmony!`, 
  `A splendid morning to you!`, 
  `Rise and sparkle like the morning dew!`, 
  `Good morning, cohort!`, 
  `Hello, dawn of a new day!`, 
  `Morning jubilation!`, 
  `Wishing you a morning full of positivity!`, 
  `Rise and thrive in the morning glow!`, 
  `Good morning, amigo!`, 
  `Hello, daybreak!`, 
  `Morning inspiration!`, 
  `A fantastic morning to you!`, 
  `Rise and let your morning glow shine!`
  ]

function printTarget(target, interaction, text){  // prints text nevertheless of the absence of target
  if (!target){
    return interaction.reply(text);
  } else {
    return interaction.reply(`${text} ${target}`);
  }
}

module.exports = {
  data : new SlashCommandBuilder()
  .setName('greeting').setDescription('Be wholesome')
  .addStringOption(option => {
    return option.setName("type")
    .setDescription("What kind of greeting do you want to say?")
    .setRequired(true)
    .addChoices(
      {name: "hello", value: "hello"},
      {name: "goodmorning", value: "goodmorning"},
      {name: "goodnight", value: "goodnight"},
      {name: "hornygoodnight", value: "hornygoodnight"}
      )
    }
  )
  .addUserOption((option) =>
  option.setName('person')
  .setDescription('Who do you want to wish goodnight?')
  .setRequired(false)
  ),


  async execute(interaction){
    const target = interaction.options.getUser("person")
    const textType = interaction.options.getString("type")

    if (textType == "hello"){
      const text = hello[Math.floor(Math.random() * hello.length)];
      printTarget(target, interaction, text);

    } else if (textType == "goodnight"){
      const text = goodnight[Math.floor(Math.random() * goodnight.length)];
      printTarget(target, interaction, text);

    } else if (textType == "goodmorning"){
      const text = goodmorning[Math.floor(Math.random() * goodmorning.length)];
      printTarget(target, interaction, text);

    } else if (textType == "hornygoodnight"){
      const text = horny_goodnight[Math.floor(Math.random() * horny_goodnight.length)];
      printTarget(target, interaction, text);

    } 
  }
}